### ISSUE TITLE
Fisher package manager?

### ISSUE THREAD

**Issue by nickeb96** [Doctusoft/google-cloud-sdk-fish-completion#4]
Would it be possible to support installation through [fisher](https://github.com/jorgebucaran/fisher)?  So we could just do `fisher add <this project>` instead.

**Comment by DrPhil** [comment]
It already is. Running
`fisher add aliz-ai/google-cloud-sdk-fish-completion`
should install this package correctly.

**Comment by nickeb96** [comment]
My mistake, thanks.
